### PR TITLE
Fix TabItem `value` assignment

### LINKED ISSUE #200: No tab item is selected when the URL includes a fragment
No fragment: https://goteleport.com/docs/connect-your-client/tsh/

Image

With a fragment: https://goteleport.com/docs/connect-your-client/tsh/#introduction

Notice how the "Self-Hosted" tab is no longer selected.

Image

### PR DESCRIPTION
**Pull request by ptgott**
Fixes #200

The current `TabItem` wrapper uses `nanoid` to assign a random value to the `value` property, which is what we did at the AST level prior to the changes in #183. This change uses `useId` instead, which is the idiomatic React technique for achieving a similar result. This approach also avoids the issue in #200.

### CODE REVIEW

File: src/theme/Tabs/index.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ export default function TabsWrapper(props: Props): ReactNode {
         ...child,
         props: {
           ...child.props,
-          value: nanoid(),
+          value: useId(),
```
Comment (ravicious) [inline src/theme/Tabs/index.tsx:31]: The number of calls to hooks must be the same between each re-render, so this will break if `props.children` ever has a different number of children between renders.

A similar problem is described in [the docs for `useRef`](https://react.dev/learn/manipulating-the-dom-with-refs#how-to-manage-a-list-of-refs-using-a-ref-callback). The solution they use there won't work here, as it's dependent on each item having a unique ID, which is the thing we want to generate for each item.

I don't know how exactly `<TabItem>` and `<Tabs>` work, but I wonder if we could get away with using an array index as the value. Alternatively, if `value` needs to be unique within some broader context, call `useId` once within the render body of `TabsWrapper` and then append an index to it here.
